name: medio_ambiente_app
description: App Ministerio de Medio Ambiente RD
publish_to: 'none'
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  video_player: ^2.9.2
  url_launcher: ^6.3.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/perfil.jpg
    - assets/logo.png

